import Navbar from "@/components/Navbar";
import "../styles/globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <section className="p-4 mx-6">{children}</section>
      </body>
    </html>
  );
}
